package webmention

import (
	"encoding/json"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

// Received types model normalised inbound mentions, written by `fetch` and read by the build
// (asset-mode display) and the browser (mentions.js). Deliberately small — not the raw
// receiver payload — and shared so the reader, cache and templates agree on one shape.

// MentionAuthor is the sender's h-card, as much as the receiver exposes.
type MentionAuthor struct {
	Name  string `json:"name,omitempty"`
	URL   string `json:"url,omitempty"`
	Photo string `json:"photo,omitempty"`
}

// Mention is one inbound interaction with a post.
type Mention struct {
	Type      string        `json:"type"` // like | repost | reply | mention
	Author    MentionAuthor `json:"author"`
	URL       string        `json:"url"`
	Content   string        `json:"content,omitempty"`
	Published string        `json:"published,omitempty"`
}

// Mentions is the per-post file (one JSON per target), served under _mentions/<key>.json.
type Mentions struct {
	Target   string    `json:"target"`
	Updated  string    `json:"updated,omitempty"`
	Mentions []Mention `json:"mentions"`
}

// KeyForURL maps a target URL (or a base_path-relative page path) to the cache/asset key —
// the path with no leading/trailing slash. Both the build (from a page's URL) and `fetch`
// (from a mention's target URL) use it so a post and its mentions land under the same key.
//
//	https://blog.example.com/posts/x/ → posts/x
//	/posts/x/                         → posts/x
//	(home) "/" or ""                  → "" (→ index)
func KeyForURL(raw string) string {
	if u, err := url.Parse(raw); err == nil && u.Host != "" {
		raw = u.Path
	}
	return strings.Trim(raw, "/")
}

// CacheDir is the local received-mentions cache directory under a project root. It is a
// derived export (regenerated by `fetch`), not preserved state — see the design doc.
func CacheDir(root string) string {
	return filepath.Join(root, ".colophon", "cache", "webmentions")
}

// cacheFile is the on-disk path for a key ("" → index.json).
func cacheFile(dir, key string) string {
	if key == "" {
		key = "index"
	}
	return filepath.Join(dir, filepath.FromSlash(key)+".json")
}

// LoadCached reads the cached Mentions for a key. A missing file is not an error — it yields
// an empty result, so a build with no fetched data renders nothing and stays green.
func LoadCached(dir, key string) (Mentions, error) {
	b, err := os.ReadFile(cacheFile(dir, key))
	if os.IsNotExist(err) {
		return Mentions{}, nil
	}
	if err != nil {
		return Mentions{}, err
	}
	var m Mentions
	if err := json.Unmarshal(b, &m); err != nil {
		return Mentions{}, err
	}
	return m, nil
}

// SaveCached writes the Mentions for a key, creating parent dirs.
func SaveCached(dir, key string, m Mentions) error {
	path := cacheFile(dir, key)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}
