package generate

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"regexp"
	"sort"
	"strings"
)

// Sidecar is the metadata written beside each generated image, so the cache is
// self-describing: it records exactly how the image was produced.
type Sidecar struct {
	Prompt        string            `json:"prompt"`
	System        string            `json:"system,omitempty"`
	Provider      string            `json:"provider"`
	Model         string            `json:"model"`
	Params        map[string]string `json:"params,omitempty"`
	MIME          string            `json:"mime"`
	RevisedPrompt string            `json:"revised_prompt,omitempty"`
	Generated     string            `json:"generated"`
}

// CacheKey is the deterministic identity of a generation request. Everything that
// affects the pixels — provider, model, prompt, system prompt, params — feeds the
// hash, so an identical request anywhere on the site collapses onto one cached image,
// and changing the model, the house style or a param produces a new one.
func CacheKey(provider, model, prompt, system string, params map[string]string) string {
	var b strings.Builder
	b.WriteString(provider)
	b.WriteByte('\n')
	b.WriteString(model)
	b.WriteByte('\n')
	b.WriteString(strings.TrimSpace(prompt))
	b.WriteByte('\n')
	b.WriteString(strings.TrimSpace(system))
	for _, k := range sortedKeys(params) {
		b.WriteByte('\n')
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(params[k])
	}
	sum := sha256.Sum256([]byte(b.String()))
	return hex.EncodeToString(sum[:])[:12]
}

// Stem is the deterministic base name WITHOUT extension for a request's image: a
// short readable slug of the prompt plus the cache key, so the file is both
// human-recognisable in the repo and collision-free. The extension is chosen from the
// generated bytes at write time, so identical requests share a stem regardless of the
// format the provider returns.
func Stem(provider, model, prompt, system string, params map[string]string) string {
	return promptSlug(prompt) + "-" + CacheKey(provider, model, prompt, system, params)
}

// SidecarPath is the metadata path for an image path (image.png → image.png.json).
func SidecarPath(imagePath string) string { return imagePath + ".json" }

// WriteSidecar writes sc as pretty JSON to the image's sidecar path.
func WriteSidecar(imagePath string, sc Sidecar) error {
	b, err := json.MarshalIndent(sc, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(SidecarPath(imagePath), append(b, '\n'), 0o644)
}

var slugCleanRE = regexp.MustCompile(`[^a-z0-9]+`)

// promptSlug reduces a prompt to a short lowercase hyphenated stem for readability.
func promptSlug(prompt string) string {
	s := slugCleanRE.ReplaceAllString(strings.ToLower(prompt), "-")
	s = strings.Trim(s, "-")
	if len(s) > 48 {
		s = strings.Trim(s[:48], "-")
	}
	if s == "" {
		s = "image"
	}
	return s
}

func sortedKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}
