#!/usr/bin/env bash
# Generate fixtures/mixed/.env from the current environment.
#
# It collects every {env:VAR} that colophon.yaml interpolates, plus the deploy secrets
# colophon reads directly from the environment, and writes them to .env as `export VAR=...`
# lines. Then, to test this fixture against your real vault / Cloudflare account:
#
#   set -a; source .env; set +a
#   colophon serve            # or: colophon build --env dist
#
# A value comes from the current shell if set, else from the existing .env (so re-running is
# non-destructive), else empty. .env is git-ignored — never commit it.
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE=.env

# Vars the config interpolates, plus the env-only deploy secrets (never in the config).
config_vars=$(grep -oE '\{env:[A-Z0-9_]+' colophon.yaml | sed 's/{env://' | sort -u)
secret_vars="CLOUDFLARE_API_TOKEN R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY"
vars=$(printf '%s\n' $config_vars $secret_vars | sort -u)

# prior <NAME>: the value of NAME in the existing .env, without touching this shell.
prior() {
  [ -f "$ENV_FILE" ] || return 0
  ( set +u; set -a; . "$ENV_FILE" >/dev/null 2>&1 || true; printf '%s' "${!1-}" )
}

tmp=$(mktemp)
{
  echo "# Generated by gen-dotenv.sh — git-ignored, do not commit."
  echo "# Usage: set -a; source .env; set +a"
  for v in $vars; do
    val="${!v-}"
    [ -n "$val" ] || val="$(prior "$v")"
    printf 'export %s=%q\n' "$v" "$val"
  done
} >"$tmp"
mv "$tmp" "$ENV_FILE"
echo "Wrote $ENV_FILE ($(grep -c '^export' "$ENV_FILE") vars). Load with: set -a; source $ENV_FILE; set +a"
